CREATE DATABASE pivotguarddb;
\c pivotguarddb;
CREATE TABLE ServiceType (
  Name varchar(50) NOT NULL,
  PRIMARY KEY (Name)
);

CREATE TABLE Site (
  ID serial NOT NULL,
  URL varchar(100) UNIQUE,
  Name varchar(80),
  IsCompromised boolean NOT NULL,
  ServiceType varchar(50),
  description varchar(350),
  PRIMARY KEY (ID),
  FOREIGN KEY (ServiceType) REFERENCES ServiceType(Name) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE ThreatType (
  ID serial NOT NULL,
  Name varchar(40) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE Threat (
  SiteID int NOT NULL,
  ThreatID int NOT NULL,
  PRIMARY KEY (SiteID, ThreatID),
  FOREIGN KEY (SiteID) REFERENCES Site(ID) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (ThreatID) REFERENCES ThreatType(ID) DEFERRABLE INITIALLY DEFERRED
);

BEGIN;
INSERT INTO ServiceType(Name)
  VALUES ('AI Assistant'),
  ('Cloud Storage'),
  ('Dating Apps'),
  ('Design Tools'),
  ('Email'),
  ('File Sharing'),
  ('Fitness and Health'),
  ('Forms'),
  ('Home Assistants'),
  ('Image Generation'),
  ('Instant Messaging'),
  ('Location Tracking'),
  ('Maps and Nav'),
  ('Menstrual Cycle Trackers'),
  ('Music Recognition'),
  ('Music Streaming'),
  ('Office'),
  ('Password Managers'),
  ('Podcast'),
  ('TikTok'),
  ('URL Shortener'),
  ('Video Streaming');

INSERT INTO ThreatType(Name)
  VALUES ('Privacy'),
  ('Trackers'),
  ('Bad Encryption'),
  ('Requires Permissions'),
  ('Data Breach'),
  ('Invasive Algorithms'),
  ('Analytics');

INSERT INTO Site (URL, Name, IsCompromised, Description) VALUES
  ('openai.com', 'OpenAI', TRUE, NULL),
  ('copilot.microsoft.com', 'Copilot', TRUE, NULL),
  ('drive.google.com', 'Google Drive', TRUE, 'Google owned, so privacy policy is very bad. The data is stored in their remote servers where you lose control of it. They use trackers. No encryption available.'),
  ('dropbox.com', 'Dropbox', TRUE, 'Bad privacy policy. The app has various trackers and requires many permissions.'),
  ('onedrive.com', 'OneDrive', TRUE, 'Microsoft owned, privacy policy is very bad. The data is stored in their remote servers where you lose control of it. They use trackers. No encryption available.'),
  ('tinder.com', 'Tinder', TRUE, NULL),
  ('grinder.com', 'Grindr', TRUE, NULL),
  ('badoo.com', 'Badoo', TRUE, NULL),
  ('lovoo.com', 'Lovoo', TRUE, NULL),
  ('adobe.com', 'Adobe', TRUE, NULL),
  ('gmail.com', 'Gmail', TRUE, NULL),
  ('outlook.com', 'Outlook', TRUE, NULL),
  ('yandex.com', 'Yandex Mail', TRUE, NULL),
  ('yahoo.com', 'Yahoo! Mail', TRUE, NULL),
  ('wetransfer.com', 'WeTransfer', TRUE, 'Bad privacy policy. Files are not e2e encrypted. Website has many analytics and trackers.'),
  ('send-anywhere.com', 'SendAnywhere', TRUE, 'No e2e encryption. Website has loads of analytics and trackers from Facebook, Google, Cloudflare...'),
  ('fitbit.com', 'Fitbit', TRUE, NULL),
  ('google.com/forms', 'Google Forms', TRUE, NULL),
  ('home.google.com', 'Google Home', TRUE, NULL),
  ('alexa.amazon.com', 'Alexa', TRUE, NULL),
  ('apple.com/siri', 'Siri', TRUE, NULL),
  ('midjourney.com', 'MidJourney', TRUE, NULL),
  ('whatsapp.com', 'WhatsApp', TRUE, NULL),
  ('instagram.com', 'Instagram DM', TRUE, NULL),
  ('messenger.com', 'Facebook Messenger', TRUE, NULL),
  ('skype.com', 'Skype', TRUE, NULL),
  ('zoom.com', 'Zoom', TRUE, NULL),
  ('chat.google.com', 'Google Chat', TRUE, NULL),
  ('google.com/android/find', 'Find My Device - Google', TRUE, NULL),
  ('google.com/maps', 'Google Maps', TRUE, NULL),
  ('apple.com/maps', 'Apple Maps', TRUE, NULL),
  ('yandex.com/maps', 'Yandex Maps', TRUE, NULL),
  ('bing.com/maps', 'Bing Maps', TRUE, NULL),
  ('waze.com', 'Waze', TRUE, NULL),
  ('sygic.com', 'Sygic', TRUE, NULL),
  ('wego.here.com', 'HERE WeGo', TRUE, NULL),
  ('petalmaps.com', 'Petal Maps', TRUE, NULL),
  ('helloclue.com', 'Clue', TRUE, NULL),
  ('shazam.com', 'Shazam', TRUE, 'It''s under Apple''s privacy policy. The android app has a few Google trackers.'),
  ('soundhound.com', 'SoundHound', TRUE, 'Has way too many trackers for a music recognition app'),
  ('music.amazon.com', 'Amazon Music', TRUE, NULL),
  ('spotify.com', 'Spotify', TRUE, 'Very bad privacy policy. Apps have many trackers. Way too many permissions are required for a streaming app.'),
  ('soundcloud.com', 'Soundcloud', TRUE, 'Dubitous priavcy policy. Apps have many trackers. Way too many permissions are required for a streaming app.'),
  ('music.youtube.com', 'Youtube Music', TRUE, NULL),
  ('office.com', 'Microsoft Office', TRUE, NULL),
  ('docs.google.com', 'Google Docs', TRUE, NULL),
  ('lastpass.com', 'LastPass', TRUE, NULL),
  ('dashlane.com', 'Dashlane', TRUE, NULL),
  ('ivoox.com', 'iVoox', TRUE, NULL),
  ('audible.com', 'Audible', TRUE, NULL),
  ('deezer.com', 'Deezer', TRUE, NULL),
  ('tiktok.com', 'TikTok', TRUE, NULL),
  ('bit.ly', 'Bitly', TRUE, NULL),
  ('netflix.com', 'Netflix', TRUE, 'Bad privacy policy. Apps have Google trackers. Many permissions are required for a streaming app.'),
  ('disneyplus.com', 'Disney Plus', TRUE, 'Very bad privacy policy. Apps have various trackers. Many permissions are required for a streaming app.'),
  ('plex.tv', 'Plex', TRUE, 'Dubitous privacy policy. Apps have many trackers. Way too many permissions are required for a streaming app.'),
  ('amazon.com', 'Amazon', TRUE, 'Bad privacy policy. Apps have Google trackers. Many permissions are required for a streaming app.'),
  ('https://github.com/ggerganov/llama.cpp', 'Llama.cpp', FALSE, 'Inference of Facebook''s LLaMA model in pure C/C++ so it can run locally on a CPU.'),
  ('https://github.com/janhq/jan', 'Jan', FALSE, 'Jan is an open source alternative to ChatGPT that runs 100% offline on your computer.'),
  ('https://github.com/go-skynet/LocalAI', 'LocalAI', FALSE, 'Self-hosted, community-driven simple local OpenAI-compatible API written in go. Can be used as a drop-in replacement for OpenAI, running on CPU with consumer-grade hardware.'),
  ('https://github.com/jmorganca/ollama', 'OLlama', FALSE, 'Get up and running with Llama 2 and other large language models locally.'),
  ('https://github.com/continuedev/continue', 'Continue', FALSE, 'Open-source autopilot for VS Code and JetBrains—the easiest way to code with any LLM'),
  ('https://github.com/fauxpilot/fauxpilot', 'FauxPilot', FALSE, 'an open-source,local alternative to GitHub Copilot server'),
  ('https://github.com/danielgross/localpilot', 'LocalPilot', FALSE, 'Use GitHub Copilot locally on your Macbook with one-click.'),
  ('https://github.com/ravenscroftj/turbopilot', 'TurboPilot', FALSE, '[Archived] Turbopilot is an open source large-language-model based code completion engine that runs locally on CPU.'),
  ('https://nextcloud.com/', 'NextCloud', FALSE, 'The open source self-hosted productivity platform that keeps you in control.'),
  ('https://www.seafile.com/en/home/', 'SeaFile', FALSE, 'High performance file syncing and sharing. It includes a Wiki, WYSIWYG editing and other knowledge management features.'),
  ('https://peergos.org/', 'Peergos', FALSE, 'Secure and private space online where you can store, share and view your photos, videos, music and documents. Also includes a calendar, news feed, task lists, chat and email client. Open source and self-hostable.'),
  ('https://proton.me/drive', 'Proton Drive', FALSE, 'End-to-end encrypted Swiss vault for your files that protects your data.'),
  ('https://private.storage/', 'PrivateStorage', FALSE, 'Accountless, privacy-focused cloud storage and folder synchronization with client-side encryption.'),
  ('https://cryptomator.org/', 'Cryptomator', FALSE, 'Cryptomator encrypts your data quickly and easily. Afterwards you upload them protected to your favorite cloud service'),
  ('https://syncthing.net/', 'Syncthing', FALSE, 'Continuous file synchronization program. It synchronizes files between two or more computers in real time, safely protected from prying eyes.'),
  ('https://rclone.org/', 'Rclone', FALSE, 'Rclone is a command line program to manage files on cloud storage. It is a feature rich alternative to cloud vendors'' web storage interfaces and like the tools listed above enables encryption for encrypting files in the cloud.'),
  ('https://restic.net/', 'Restic', FALSE, 'Restic is also command line program to manage files on various cloud storage providers. Restic uses encryption by default. Few noteworthy features of restic include browsing through storage as git like snapshots at no extra storage cost, deduplication and significant savings through compression.'),
  ('https://alovoa.com/', 'Alovoa', FALSE, 'Free and open-source dating platform that respects your privacy.'),
  ('https://www.scribus.net/', 'Scribus', FALSE, 'a free and open-source desktop publishing (DTP) software available for most desktop operating systems. It is designed for layout, typesetting, and preparation of files for professional-quality image-setting equipment. Scribus can also create animated and interactive PDF presentations and forms.'),
  ('https://www.gimp.org/', 'GIMP', FALSE, 'A free and open-source raster graphics editor used for image manipulation (retouching) and image editing, free-form drawing, transcoding between different image file formats, and more specialized tasks. It is not designed to be used for drawing, though some artists and creators have used it in this way.'),
  ('https://inkscape.org/', 'Inkscape', FALSE, 'A free and open-source vector graphics editor for GNU/Linux, Windows and macOS. It offers a rich set of features and is widely used for both artistic and technical illustrations such as cartoons, clip art, logos, typography, diagramming and flowcharting.'),
  ('https://krita.org/', 'Krita', FALSE, 'A free and open-source raster graphics editor designed primarily for digital art and 2D animation.'),
  ('https://github.com/excalidraw/excalidraw', 'Excalidraw', FALSE, 'Virtual whiteboard for sketching hand-drawn like diagrams.'),
  ('https://penpot.app/', 'Penpot', FALSE, 'Penpot is an Open Source design and prototyping platform for product teams.'),
  ('https://forwardemail.net/', 'Forward Email', FALSE, 'the 100% open-source and privacy-focused email service.'),
  ('https://protonmail.com/', 'ProtonMail', FALSE, 'Secure Email. Based in Switzerland.'),
  ('https://tuta.com/', 'Tuta', FALSE, 'Secure email for everybody. Open Source.'),
  ('https://riseup.net/en/about-us', 'Riseup', FALSE, 'Online communication tools for people and groups working on liberatory social change.'),
  ('https://mailfence.com/', 'Mailfence', FALSE, 'Secure and private email.'),
  ('https://github.com/docker-mailserver/docker-mailserver', 'Docker mail server', FALSE, 'A fullstack but simple mail server (SMTP, IMAP, LDAP, Antispam, Antivirus, etc.) using Docker.'),
  ('https://github.com/mailcow/mailcow-dockerized', 'Mailcow: dockerized', FALSE, 'The mailserver suite with the ''moo''.'),
  ('https://github.com/mail-in-a-box/mailinabox', 'Mail-in-a-box', FALSE, 'Mail-in-a-Box helps individuals take back control of their email by defining a one-click, easy-to-deploy SMTP+everything else server: a mail server in a box.'),
  ('https://github.com/mjl-/mox', 'Mox', FALSE, 'Modern full-featured open source secure mail server for low-maintenance self-hosted email.'),
  ('https://github.com/M66B/FairEmail', 'FairEmail', FALSE, 'Fully featured, open source, privacy friendly email app for Android.'),
  ('https://k9mail.app/', 'K9', FALSE, 'Open Source Email App for Android.'),
  ('https://www.thunderbird.net/', 'Thunderbird', FALSE, 'A free customizable open source email client.'),
  ('https://github.com/simple-login/app', 'SimpleLogin', FALSE, 'With email aliases, you can finally create a different identity for each website. Defend against spams, phishing and data breach. You can choose self-hosting or you can also use their own platform as a service.'),
  ('https://github.com/anonaddy/anonaddy', 'AnonAddy', FALSE, 'With email aliases, you can finally create a different identity for each website. Defend against spams, phishing and data breach. You can choose self-hosting or you can also use their own platform as a service.'),
  ('https://blaze.now.sh/', 'Blaze', FALSE, 'A fast, p2p and radically different way to transfer files.'),
  ('https://github.com/blindnet-io/blindsend', 'Blindsend', FALSE, 'Open source tool for private, end-to-end encrypted file exchange.'),
  ('https://github.com/schollz/croc', 'Croc', FALSE, 'Easily and securely send things from one computer to another.'),
  ('https://github.com/tom-james-watson/dat-cp', 'Dat-cp', FALSE, 'Copy files between hosts on a network using the peer-to-peer Dat network.'),
  ('https://leastauthority.com/community-matters/destiny/', 'Destiny', FALSE, 'Send files directly to the receiver in real-time. Developed for and with HROs as a free Privacy Enhancing Technology alternative.'),
  ('https://framagit.org/fiat-tux/hat-softwares/lufi', 'Lufi', FALSE, 'Let''s Upload that FIle — File sharing software.'),
  ('https://localsend.org/', 'Localsend', FALSE, 'Share files to nearby devices. Free, open source, cross-platform.'),
  ('https://github.com/magic-wormhole/magic-wormhole', 'Magic Wormhole', FALSE, 'Get things from one computer to another, safely.'),
  ('https://github.com/micahflee/onionshare', 'OnionShare', FALSE, 'An open source tool that lets you securely and anonymously share files, host websites, and chat with friends using the Tor network.'),
  ('https://github.com/paperless-ngx/paperless-ngx', 'Paperless-ngx', FALSE, 'A community-supported supercharged version of paperless based on paperless-ng'),
  ('https://github.com/schlagmichdoch/PairDrop', 'PairDrop', FALSE, 'An improved version of Snapdrop that also allows you to pair devices and share files outside your network.'),
  ('https://github.com/SpatiumPortae/portal', 'Portal', FALSE, 'A command-line file transfer utility for sending encrypted files from any computer to another.'),
  ('https://github.com/claudiodangelis/qrcp', 'QRcp', FALSE, 'Transfer files over wifi from your computer to your mobile device by scanning a QR code without leaving the terminal.'),
  ('https://gitlab.com/timvisee/send', 'Send', FALSE, 'Simple, private file sharing. (Mozilla Send Fork)'),
  ('https://github.com/marchellodev/sharik', 'Sharik', FALSE, 'Sharik works with Wi-Fi connection or Tethering (Wi-Fi Hotspot). No internet connection needed. Available for Android, iOS, Linux, MacOS & Windows.'),
  ('https://github.com/RobinLinus/snapdrop', 'Snapdrop', FALSE, 'A Progressive Web App for local file sharing inspired by Apple''s Airdrop.'),
  ('https://winden.app/', 'Winden', FALSE, 'A convenient version of Magic Wormhole you can use from within your browser. No need to install an app.'),
  ('https://github.com/jhaals/yopass', 'Yopass', FALSE, 'Secure sharing of secrets, passwords and files.'),
  ('https://codeberg.org/jannis/FitoTrack', 'Fitotrack', FALSE, 'A privacy oriented fitness tracker for Android.'),
  ('https://github.com/OpenTracksApp/OpenTracks', 'OpenTracks', FALSE, 'OpenTracks is a sport tracking application that completely respects your privacy.'),
  ('https://codeberg.org/Freeyourgadget/Gadgetbridge', 'Gadgetbridge', FALSE, 'A free and cloudless replacement for your gadget vendors'' closed source Android applications.'),
  ('https://wger.de/en/software/features', 'wger', FALSE, 'A free, open source, self-hosted web application that manages your exercises, workouts and nutrition.'),
  ('https://github.com/Vincenius/workout-lol', 'workout.lol', FALSE, 'A small web application to create workouts based on your available equipment and the muscles you want to train that you can selfhost.'),
  ('https://world.openfoodfacts.org/', 'OpenFoodFacts', FALSE, 'Open Food Facts is a food products database made by everyone, for everyone. You can use it to make better food choices.'),
  ('https://typebot.io/', 'TypeBot', FALSE, 'Open-source conversational forms.'),
  ('https://cryptpad.fr/form/', 'CryptPad Forms', FALSE, 'Part of the Cryptpad end-to-end encrypted and open-source collaboration suite.'),
  ('https://framaforms.org/', 'FramaForms', FALSE, 'Design your online surveys easily while respecting your audience.'),
  ('https://mycroft.ai/', 'Mycroft', FALSE, 'The Private and Open Voice Assistant.'),
  ('https://www.home-assistant.io/', 'Home Assistant', FALSE, 'Open source home automation that puts local control and privacy first.'),
  ('https://github.com/AUTOMATIC1111/stable-diffusion-webui', 'Stable Diffusion', FALSE, 'High-Resolution Image Synthesis with Latent Diffusion Models.'),
  ('https://matrix.org/', 'Matrix', FALSE, 'An open network for secure, decentralized communication.'),
  ('https://xmpp.org/', 'Jabber / XMPP', FALSE, 'The universal and open messaging standard. Tried and tested. Independent. Privacy-focused. E2E encrypted.'),
  ('https://delta.chat/', 'DeltaChat', FALSE, 'Chat over encrypted e-mail.'),
  ('https://getsession.org/', 'Session', FALSE, 'Extreme focus on privacy and anonymity. Blockchain technology.'),
  ('https://simplex.chat/', 'SimpleX Chat', FALSE, 'The first chat platform that is 100% private by design - it has no access to your connection graph.'),
  ('https://status.im/', 'Status', FALSE, 'Status is a secure messaging app, crypto wallet, and Web3 browser built with state of the art technology.'),
  ('https://threema.ch/en', 'Threema', FALSE, 'The messenger that puts security and privacy first. Pay once, chat forever. No collection of user data. Open Source client.'),
  ('https://signal.org/', 'Signal', FALSE, 'Extreme focus on privacy, combined with all of the features you expect. Strong encryption by design. 100% Open Source.'),
  ('https://tox.chat/', 'Tox', FALSE, 'Tox is easy-to-use software that connects you with friends and family without anyone else listening in.'),
  ('https://briarproject.org/', 'Briar', FALSE, 'Peer-to-peer encrypted messaging and forums.'),
  ('https://github.com/maqp/tfc', 'Tinfoil Chat', FALSE, 'Onion-routed, endpoint secure messaging system.'),
  ('https://berty.tech/', 'Berty', FALSE, 'The privacy-first messaging app that works with or without internet access, cellular data or trust in the network.'),
  ('https://keyoxide.org/', 'Keyoxide', FALSE, 'A modern, secure and privacy-friendly platform to establish your decentralized online identity.'),
  ('https://github.com/EddieHubCommunity/BioDrop', 'BioDrop', FALSE, 'Connect to your audience with a single link. Showcase the content you create and your projects in one place. Make it easier for people to find, follow and subscribe.'),
  ('https://linkstack.org/', 'LinkStack', FALSE, 'Self-hosted open-source Linktree alternative.'),
  ('https://apps.nextcloud.com/apps/phonetrack', 'Nextcloud Phonetrack', FALSE, 'Nextcloud app to track location history with an Android app (other apps also supported). Supports caching positions offline and sending them to the server in batches. The first-party app has good battery saving options.'),
  ('https://owntracks.org/', 'OwnTracks', FALSE, 'Location tracking for displaying the current location only (limited location history functionality).'),
  ('https://www.traccar.org/', 'Traccar', FALSE, 'Location tracking software made for dedicated GPS logging devices.'),
  ('https://github.com/Freika/dawarich', 'Dawarich', FALSE, 'Self-hosted alternative to Google Location History.'),
  ('https://gitlab.com/Nulide/findmydevice', 'Find My Device', FALSE, 'Find your Android Device via SMS.'),
  ('https://github.com/mendhak/gpslogger', 'GPSlogger', FALSE, 'Lightweight GPS Logging Application For Android. No servers, no internet. Saved to a simple file to local storage.'),
  ('https://www.openstreetmap.org/', 'Open Street Map (OSM)', FALSE, 'OpenStreetMap is built by a community of mappers that contribute and maintain data about roads, trails, cafés, railway stations, and much more, all over the world.'),
  ('https://osmand.net/', 'OSMAnd', FALSE, 'Android/iOS Navigation app using OSM. It is a feature-rich app with all you expect.'),
  ('https://map.qwant.com/', 'Qwant Maps', FALSE, 'An OpenStreetMap-based private Google Maps alternative.'),
  ('https://organicmaps.app/', 'Organic Maps', FALSE, 'Great offline maps for hikers and cyclists.'),
  ('https://gitlab.com/ngrob/bluemoon-android', 'Bluemoon', FALSE, 'Open source, privacy friendly menstruation tracking app. Your period, your data!'),
  ('https://dripapp.org/', 'Drip', FALSE, 'Menstrual cycle and fertility tracking. Everything you enter stays on your device.'),
  ('https://eukiapp.org/', 'Euki', FALSE, 'The period tracker that doesn''t track you.'),
  ('https://github.com/wildeyedskies/log28', 'log28', FALSE, 'a (very) simple no-frills period tracker for Android.'),
  ('https://github.com/arnowelzel/periodical', 'Periodical', FALSE, 'A calendar to track your menstruation and calculate possible fertile days.'),
  ('https://github.com/marin-m/SongRec', 'SongRec', FALSE, 'An open-source Shazam client for Linux, written in Rust.'),
  ('https://github.com/smcclennon/SongID', 'SongID Telegram Bot', FALSE, 'A Telegram bot that can identify music in audio/video files you send it.'),
  ('https://funkwhale.audio/', 'Funkwhale', FALSE, 'A social platform to enjoy and share music.'),
  ('https://www.subsonic.org/pages/index.jsp', 'Subsonic', FALSE, 'Your complete, personal music streamer.'),
  ('https://ampache.org/', 'Ampache', FALSE, 'A web based audio/video streaming application and file manager.'),
  ('https://koel.dev/', 'Koel', FALSE, 'a personal music streaming server that works.'),
  ('https://nuclear.js.org/', 'Nuclear', FALSE, 'Modern music player focused on streaming from free sources.'),
  ('https://navidrome.org/', 'NaviDrome', FALSE, 'Lightweight, fast and self-contained personal music streamer.'),
  ('https://github.com/moritz-weber/mucke', 'Mucke', FALSE, 'A music player for local files with unique custom playback options.'),
  ('https://github.com/snuffyDev/Beatbump', 'BeatPump', FALSE, 'Alternative frontend for YouTube Music; no ads and custom API wrapper.'),
  ('https://github.com/vfsfitvnm/ViMusic', 'ViMusic', FALSE, '[Unmantained] A Jetpack Compose Android application for streaming music from YouTube Music.'),
  ('https://www.libreoffice.org/', 'LibreOffice', FALSE, 'Free and open source offline office.'),
  ('https://www.onlyoffice.com/', 'OnlyOffice', FALSE, 'Free and open source online office for collaboration.'),
  ('https://cryptpad.fr/form//', 'Cryptpad', FALSE, 'Collaboration suite, encrypted and open-source.'),
  ('https://etherpad.org/', 'Etherpad', FALSE, 'Highly customizable open source online editor providing collaborative editing in really real-time.'),
  ('https://bitwarden.com/', 'Bitwarden', FALSE, 'An open source cloud based password manager.'),
  ('https://keepassxc.org/', 'KeepassXC', FALSE, 'Securely store passwords using industry standard encryption, no sync just storage.'),
  ('https://www.lesspass.com/', 'LessPass', FALSE, 'Stateless password manager. Remember one master password to access your passwords. No sync needed.'),
  ('https://padloc.app/', 'Padloc', FALSE, 'The last password manager you''ll ever want to use.'),
  ('https://www.passbolt.com/', 'Passbolt', FALSE, 'An open source password manager designed for team collaboration.'),
  ('https://passky.org/', 'Passky', FALSE, 'Simple, modern, lightweight, open-source and secure password manager.'),
  ('https://proton.me/pass', 'Proton Pass', FALSE, 'Open-source and encrypted password manager by Proton.'),
  ('https://crypt.fyi/', 'crypt.fyi', FALSE, 'Ephemeral zero-knowledge sensitive data sharing platform with web, cli, and chrome-extension clients'),
  ('https://github.com/bokub/nopaste', 'NoPaste', FALSE, 'Open Source pastebin alternative that works with no database, and no back-end code. Instead, the data is compressed and stored entirely in the link that you share, nowhere else.'),
  ('https://github.com/PrivateBin/PrivateBin', 'PrivateBin', FALSE, 'A minimalist, open source online pastebin where the server has zero knowledge of pasted data. Data is encrypted/decrypted in the browser using 256 bits AES.'),
  ('https://antennapod.org/', 'Antennapod', FALSE, 'A podcast player that is completely open. Subscribe to any RSS feed.'),
  ('https://castopod.org/', 'Castopod', FALSE, 'Self-host your podcasts with ease, keep control over what you create and talk to your audience without any middleman. Your podcast and your audience belong to you and you only.'),
  ('https://github.com/pablouser1/ProxiTok', 'ProxiTok', FALSE, NULL),
  ('https://maglit.me/', 'Maglit', FALSE, 'An encrypted and privacy respecting Link Shortener service that also supports Magnet Links'),
  ('https://github.com/dubinc/dub', 'Dub', FALSE, 'You can self-host Dub.co for greater control over your data and design'),
  ('https://yourls.org/', 'Yourls', FALSE, 'Self hosted URL shortener in PHP'),
  ('https://jellyfin.org/', 'JellyFin', FALSE, 'Jellyfin is the volunteer-built media solution that puts you in control of your media. Stream to any device from your own server, with no strings attached.'),
  ('https://github.com/Dusk-Labs/dim', 'Dim', FALSE, 'Dim is a self-hosted media manager. With minimal setup, Dim will organize and beautify your media collections, letting you access and play them anytime from anywhere.'),
  ('https://www.stremio.com/', 'Stremio', FALSE, 'Stremio is a modern media center that''s a one-stop solution for your video entertainment.');

COMMIT;